[[DAQP]]
arch = "aarch64"
git-tree-sha1 = "fc8eaed9f880c6d791265bc7f116b81f61dd906c"
os = "macos"

    [[DAQP.download]]
    sha256 = "e133383e89f1eae1f207f4e2395d8026ecb7455ebca8990b7921baa4babd4c22"
    url = "https://github.com/baggepinnen/DAQP_jll.jl/releases/download/DAQP-v0.10.8+0/DAQP.v0.10.8.aarch64-apple-darwin.tar.gz"
[[DAQP]]
arch = "aarch64"
git-tree-sha1 = "e6d6dad14a3e0c880d7166f4fe2c795bde0f76f2"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "c1ed7294d7d138cd02959f61082d6306dc36cadd0744035a25ea790f1bce8247"
    url = "https://github.com/baggepinnen/DAQP_jll.jl/releases/download/DAQP-v0.10.8+0/DAQP.v0.10.8.aarch64-linux-gnu.tar.gz"
[[DAQP]]
arch = "aarch64"
git-tree-sha1 = "362110f09d59b2890be70e03d6969631d3dfc517"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "7b600f613d46e54a85a419ae52f61d8a560fad346c4a926e2c0a12159a2b283e"
    url = "https://github.com/baggepinnen/DAQP_jll.jl/releases/download/DAQP-v0.10.8+0/DAQP.v0.10.8.aarch64-linux-musl.tar.gz"
[[DAQP]]
arch = "aarch64"
git-tree-sha1 = "ac1ed9febfccc2e0117a06e0371c9c3cb377aa94"
os = "freebsd"

    [[DAQP.download]]
    sha256 = "edca6bffe2382072c5bf812029f6c25ab3b565fc6189546b03b46086d5f36b6f"
    url = "https://github.com/baggepinnen/DAQP_jll.jl/releases/download/DAQP-v0.10.8+0/DAQP.v0.10.8.aarch64-unknown-freebsd.tar.gz"
[[DAQP]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1f116998f436d03d06dc35d1f777bfa3de821ec1"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "7cb6f299154ff92cab84755efa4fc9890a978ad5c53f91073ba1522641c77c5d"
    url = "https://github.com/baggepinnen/DAQP_jll.jl/releases/download/DAQP-v0.10.8+0/DAQP.v0.10.8.armv6l-linux-gnueabihf.tar.gz"
[[DAQP]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "52e8e2836a89aa83f0ec7fd128e3ab0576ceb3cb"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "919bd004b2531ba10572faf70fe4f1af5d977b578cd9bce229db942703c2ed1b"
    url = "https://github.com/baggepinnen/DAQP_jll.jl/releases/download/DAQP-v0.10.8+0/DAQP.v0.10.8.armv6l-linux-musleabihf.tar.gz"
[[DAQP]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cc7231a6444908913fb6792318e74050dcccdbe5"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "0822a13fdbba72da892ed087197d0e0d14de61f92a9258b97392ad6ffbeb3400"
    url = "https://github.com/baggepinnen/DAQP_jll.jl/releases/download/DAQP-v0.10.8+0/DAQP.v0.10.8.armv7l-linux-gnueabihf.tar.gz"
[[DAQP]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f5dc0f877d27fa54d750cb197086c68f724a06f6"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "1267e08079c704b7108aba4bfd24837e4a1ae58851640f72070edd650cf53894"
    url = "https://github.com/baggepinnen/DAQP_jll.jl/releases/download/DAQP-v0.10.8+0/DAQP.v0.10.8.armv7l-linux-musleabihf.tar.gz"
[[DAQP]]
arch = "i686"
git-tree-sha1 = "73795ef11052d34c30324f1cf1318f04a99a8020"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "a46f2f923ebcfe685e26eccaf29ef228f7db9b07b0413fddddcefa1d97a5cdd8"
    url = "https://github.com/baggepinnen/DAQP_jll.jl/releases/download/DAQP-v0.10.8+0/DAQP.v0.10.8.i686-linux-gnu.tar.gz"
[[DAQP]]
arch = "i686"
git-tree-sha1 = "a3b4009abeed806e63ba2d2b957784ab91bcf1fa"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "3e1444a4283bccbe86d13df08c3448e87c5fe82e475032288a47dcbfd8028202"
    url = "https://github.com/baggepinnen/DAQP_jll.jl/releases/download/DAQP-v0.10.8+0/DAQP.v0.10.8.i686-linux-musl.tar.gz"
[[DAQP]]
arch = "i686"
git-tree-sha1 = "0996874b178021e378f5efc78f85254d549b77af"
os = "windows"

    [[DAQP.download]]
    sha256 = "36a5aa386b5c8dc4a0b04f7367fe7b423713a7590a68b0fd0e219aed08f66a53"
    url = "https://github.com/baggepinnen/DAQP_jll.jl/releases/download/DAQP-v0.10.8+0/DAQP.v0.10.8.i686-w64-mingw32.tar.gz"
[[DAQP]]
arch = "powerpc64le"
git-tree-sha1 = "684511535c271375a0def80bb7637babac6f6ffb"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "c25b4b6e568a923543e8967d3c0a066b782c4f8833e4464f09ca55e19f5097df"
    url = "https://github.com/baggepinnen/DAQP_jll.jl/releases/download/DAQP-v0.10.8+0/DAQP.v0.10.8.powerpc64le-linux-gnu.tar.gz"
[[DAQP]]
arch = "riscv64"
git-tree-sha1 = "0eca4cd1a112be90d6b630205d4f1f451f7705a7"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "6197f8ac0d30b5a85204a9b049d11ba83bc41fd58df0771f932677c08ef96935"
    url = "https://github.com/baggepinnen/DAQP_jll.jl/releases/download/DAQP-v0.10.8+0/DAQP.v0.10.8.riscv64-linux-gnu.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "85a2852c0e02bf206f36dd6b8d316615843bcb15"
os = "macos"

    [[DAQP.download]]
    sha256 = "29d87254ec900fcff4e0c23e134f9d2eb3ad9c532d4ff6d1ff254ffe7173646d"
    url = "https://github.com/baggepinnen/DAQP_jll.jl/releases/download/DAQP-v0.10.8+0/DAQP.v0.10.8.x86_64-apple-darwin.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "60fbd3d7925ac7449f12788876c97241437f5550"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "e5b069a0ec67c995bc628184763b0f3ad979b575a591308d6af9abd44cb81273"
    url = "https://github.com/baggepinnen/DAQP_jll.jl/releases/download/DAQP-v0.10.8+0/DAQP.v0.10.8.x86_64-linux-gnu.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "a7cce97da540de9f3e664287c2dafc60a049ac19"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "fe96483fe92ab8f330a58e8b10abe6c96e714affc4756ae6e5924852e3a75812"
    url = "https://github.com/baggepinnen/DAQP_jll.jl/releases/download/DAQP-v0.10.8+0/DAQP.v0.10.8.x86_64-linux-musl.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "f3606063456e404e6d9dc8dc947d6724a5229f7a"
os = "freebsd"

    [[DAQP.download]]
    sha256 = "2bc39f7fe17b7a23b787153bf7d228087a33221e05f256bba42b7e8762989afd"
    url = "https://github.com/baggepinnen/DAQP_jll.jl/releases/download/DAQP-v0.10.8+0/DAQP.v0.10.8.x86_64-unknown-freebsd.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "34715444253da5b9e4ed38bcf064b5fb01a26421"
os = "windows"

    [[DAQP.download]]
    sha256 = "6e4079cfabe14047cb176086c2062196dc1ef9f58b5c2e718f8ba78e0643fc91"
    url = "https://github.com/baggepinnen/DAQP_jll.jl/releases/download/DAQP-v0.10.8+0/DAQP.v0.10.8.x86_64-w64-mingw32.tar.gz"
