[[DAQP]]
arch = "aarch64"
git-tree-sha1 = "1268854588d15f8e6f4c279d31d8067e423711e5"
os = "macos"

    [[DAQP.download]]
    sha256 = "4d86d130aef1af638680c86ab2f3dcb0e282a0d8e57d77c0b02b5b475d2b6e5a"
    url = "https://github.com/baggepinnen/DAQP_jll.jl/releases/download/DAQP-v0.10.7+0/DAQP.v0.10.7.aarch64-apple-darwin.tar.gz"
[[DAQP]]
arch = "aarch64"
git-tree-sha1 = "9847557d265102eb0280ad8c8371a901f601f8d7"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "1233e753956d58a24f4b11a3b37b92fb5096c2cde93772455e130da12ef6da1b"
    url = "https://github.com/baggepinnen/DAQP_jll.jl/releases/download/DAQP-v0.10.7+0/DAQP.v0.10.7.aarch64-linux-gnu.tar.gz"
[[DAQP]]
arch = "aarch64"
git-tree-sha1 = "ab929b23c06421403d17654cd38f54243d14d31b"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "89deddac39540caf52d25b50d344c91e9aefa4b3dec460dad736c78022a614f0"
    url = "https://github.com/baggepinnen/DAQP_jll.jl/releases/download/DAQP-v0.10.7+0/DAQP.v0.10.7.aarch64-linux-musl.tar.gz"
[[DAQP]]
arch = "aarch64"
git-tree-sha1 = "f177dbdc20d0a0a28278d2125f19728b68927d34"
os = "freebsd"

    [[DAQP.download]]
    sha256 = "3ce1f5257749dfa3369b849a40b1f305b2f953692c21fba3473d6585a6096378"
    url = "https://github.com/baggepinnen/DAQP_jll.jl/releases/download/DAQP-v0.10.7+0/DAQP.v0.10.7.aarch64-unknown-freebsd.tar.gz"
[[DAQP]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "564e02442eaf24ae5fa95495843057a82f101d78"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "db41f880656357a298ed77defc6db72f2bcb64b2b7954033031368071d053b3b"
    url = "https://github.com/baggepinnen/DAQP_jll.jl/releases/download/DAQP-v0.10.7+0/DAQP.v0.10.7.armv6l-linux-gnueabihf.tar.gz"
[[DAQP]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e65ba739e920821f1eefb07c3bd7c23adb38c0c8"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "8653a8d1037221cb4fbc974c45e7f9c7ae908c899dbea77920ac2c2176757bd3"
    url = "https://github.com/baggepinnen/DAQP_jll.jl/releases/download/DAQP-v0.10.7+0/DAQP.v0.10.7.armv6l-linux-musleabihf.tar.gz"
[[DAQP]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d9e61f3b6430e700d10d134c13ff0d0fdae85319"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "f2d914b90fb11bc6e23879709d59f9a82c08a3336433cfbb3b1cf3318dfa1909"
    url = "https://github.com/baggepinnen/DAQP_jll.jl/releases/download/DAQP-v0.10.7+0/DAQP.v0.10.7.armv7l-linux-gnueabihf.tar.gz"
[[DAQP]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0dd53d1de942db174744e5db6f73999304144db7"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "319b3725969f464ced85ce310f73a59ad7e55030fafe293829acbc8a081f42d1"
    url = "https://github.com/baggepinnen/DAQP_jll.jl/releases/download/DAQP-v0.10.7+0/DAQP.v0.10.7.armv7l-linux-musleabihf.tar.gz"
[[DAQP]]
arch = "i686"
git-tree-sha1 = "112b7e8137fddcdf71ddcd0c9eaabf03fa35ef4b"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "af8d66e1fd99dd9edddabbd86e1cf9544db149b33961f510330ffe9417cb96a7"
    url = "https://github.com/baggepinnen/DAQP_jll.jl/releases/download/DAQP-v0.10.7+0/DAQP.v0.10.7.i686-linux-gnu.tar.gz"
[[DAQP]]
arch = "i686"
git-tree-sha1 = "4d5bf62568fc6788f21d8b558f1f1f68f1e3b891"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "7fb9ce738bfd17cfea2419283db59cc91cc4a04ff653f7146f8ebe1b383320ee"
    url = "https://github.com/baggepinnen/DAQP_jll.jl/releases/download/DAQP-v0.10.7+0/DAQP.v0.10.7.i686-linux-musl.tar.gz"
[[DAQP]]
arch = "i686"
git-tree-sha1 = "aefcec0add3f3e197a1d4d778e1db2efcd9e049d"
os = "windows"

    [[DAQP.download]]
    sha256 = "aa89d28ba60459b17649544bff09148149cf8d2db573ecc0a1e0846d7d93912c"
    url = "https://github.com/baggepinnen/DAQP_jll.jl/releases/download/DAQP-v0.10.7+0/DAQP.v0.10.7.i686-w64-mingw32.tar.gz"
[[DAQP]]
arch = "powerpc64le"
git-tree-sha1 = "af467ac157418e8008f007b8b9d7ff6c1c6ea3f5"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "b8e7f1c7dd58dc52e45f13eb3eb9827255c3a10a2d77a56af3771acc8c58cd6c"
    url = "https://github.com/baggepinnen/DAQP_jll.jl/releases/download/DAQP-v0.10.7+0/DAQP.v0.10.7.powerpc64le-linux-gnu.tar.gz"
[[DAQP]]
arch = "riscv64"
git-tree-sha1 = "dbb4121759b6fb36cf28688a53b388218eaa8e39"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "52dd06d58508cced71491e7aa07787ad70ed1fbd876dd7981f308a07897bde40"
    url = "https://github.com/baggepinnen/DAQP_jll.jl/releases/download/DAQP-v0.10.7+0/DAQP.v0.10.7.riscv64-linux-gnu.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "27488805de8a0590315a9d39ce20d264e438c83b"
os = "macos"

    [[DAQP.download]]
    sha256 = "6f23fca732a6a969ef46ffa8de6d81873b2bec219480b228774590fe981ddd4e"
    url = "https://github.com/baggepinnen/DAQP_jll.jl/releases/download/DAQP-v0.10.7+0/DAQP.v0.10.7.x86_64-apple-darwin.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "2b145af06b31aec522f356e2b37d04a55b2c96bd"
libc = "glibc"
os = "linux"

    [[DAQP.download]]
    sha256 = "b8b3f81183db430997387f3eec24afd19e4df2dd5bae905fa63deadf196fec19"
    url = "https://github.com/baggepinnen/DAQP_jll.jl/releases/download/DAQP-v0.10.7+0/DAQP.v0.10.7.x86_64-linux-gnu.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "175760f022f1364f4a760b003f4aecf09e296056"
libc = "musl"
os = "linux"

    [[DAQP.download]]
    sha256 = "3e1c8f4eb7bacef01161240edb3848ef7fea7fd9bbb98cf04eb11d75895e54bd"
    url = "https://github.com/baggepinnen/DAQP_jll.jl/releases/download/DAQP-v0.10.7+0/DAQP.v0.10.7.x86_64-linux-musl.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "76f83c94196b665c839c5e385657d47dcdb9e3e0"
os = "freebsd"

    [[DAQP.download]]
    sha256 = "c1a945a917ab02a2908eecc3d7e270880322250187196af398061421c2146dd5"
    url = "https://github.com/baggepinnen/DAQP_jll.jl/releases/download/DAQP-v0.10.7+0/DAQP.v0.10.7.x86_64-unknown-freebsd.tar.gz"
[[DAQP]]
arch = "x86_64"
git-tree-sha1 = "b2b7ce5443f5b0f55e42571aa272d3787fa5b3c3"
os = "windows"

    [[DAQP.download]]
    sha256 = "b679456f69f0e8b9b4b9f610f4fcdee895373f5e55e08192757c572232ab171f"
    url = "https://github.com/baggepinnen/DAQP_jll.jl/releases/download/DAQP-v0.10.7+0/DAQP.v0.10.7.x86_64-w64-mingw32.tar.gz"
