# Autogenerated wrapper script for DAQP_jll for i686-w64-mingw32
export libdaqp

JLLWrappers.@generate_wrapper_header("DAQP")
JLLWrappers.@declare_library_product(libdaqp, "libdaqp.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libdaqp,
        "bin\\libdaqp.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
