# Autogenerated wrapper script for DAQP_jll for riscv64-linux-gnu
export libdaqp

JLLWrappers.@generate_wrapper_header("DAQP")
JLLWrappers.@declare_library_product(libdaqp, "libdaqp.so.0.10")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libdaqp,
        "lib/libdaqp.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
