# Autogenerated wrapper script for DAQP_jll for x86_64-apple-darwin
export libdaqp

JLLWrappers.@generate_wrapper_header("DAQP")
JLLWrappers.@declare_library_product(libdaqp, "@rpath/libdaqp.0.10.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libdaqp,
        "lib/libdaqp.0.10.3.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
